armsr: armv8: fix field_get collision in renesas irqchip
Two Renesas irqchip drivers define their own field_get macro, which
conflicts with the field_get macro backported from v6.19.

drivers/irqchip/irq-renesas-rzv2h.c:92:9: error: "field_get" redefined [-Werror]
   92 | #define field_get(_mask, _reg) (((_reg) & (_mask)) >> (ffs(_mask) - 1))
      |         ^~~~~~~~~
In file included from drivers/irqchip/irq-renesas-rzv2h.c:12:
./include/linux/bitfield.h:298:9: note: this is the location of the previous definition
  298 | #define field_get(mask, reg)                                            \
      |         ^~~~~~~~~
cc1: all warnings being treated as errors

drivers/soc/renesas/rz-sysc.c:19:9: error: "field_get" redefined [-Werror]
   19 | #define field_get(_mask, _reg) (((_reg) & (_mask)) >> (ffs(_mask) - 1))
      |         ^~~~~~~~~
....
                 from drivers/soc/renesas/rz-sysc.c:9:
./include/linux/bitfield.h:298:9: note: this is the location of the previous definition
  298 | #define field_get(mask, reg)                                            \
      |         ^~~~~~~~~

We will temporarily workaround this, pending further investigation.

Signed-off-by: Mathew McBride <matt@traverse.com.au>